add help message
devnoname120/vitacompanion pull request #16
Opened 2021-04-11 18:13 UTC by Jan200101

essentially just #12

the output has been streamlined and doesn't contain info like argument count or type
![image](https://user-images.githubusercontent.com/15076013/114315941-9d399000-9b01-11eb-8e29-bb6d7568d327.png)

There is a problem though (which also existed with the previous implementation
currently we are given no more than a 60 char array which means we are essentially causing a stack overflow and potentially causing harm elsewhere
https://github.com/devnoname120/vitacompanion/blob/7dc195d5ecbf73133213a01cdd19f31a4b573e6b/src/cmd.c#L68

I think the best solution right now would be to increase res_msga and use strn* family of functions to ensure we do not overflow
but this results in problems in the future if more commands are going to be added so perhaps having the functions allocate to the heap, return the pointer and free it after we are done sending is the better way?

2021-04-14 17:30 UTC, Jan200101 commented
I've done the exact thing I proposed at the bottom on this second branch
https://github.com/Jan200101/vitacompanion/commit/99fabc868537b985d5191085db8ea80ebbd4dda8
instead of copying into a char array we now return a pointer and mark if a command will return allocated memory or not.

For the sake of it I also rewrote the help function on that branch to be less naive and calculate the memory needed before allocating it on the heap and returning it to handler which passes it back to the thread in a struct that tells it if it needs to free it or not

2021-04-14 20:16 UTC, devnoname120 requested changes

2021-04-14 20:16 UTC, devnoname120 commented on src/cmd_definitions.c
> +  char buf[200];
```suggestion
  char buf[2000] = {0};
```

2021-04-14 20:16 UTC, devnoname120 commented on src/cmd_definitions.c
> +    if (cmd_length > longest_cmd) longest_cmd = cmd_length;
```suggestion
    if (cmd_length > longest_cmd) {
      longest_cmd = cmd_length;
    }
```

2021-04-14 20:16 UTC, devnoname120 commented on src/cmd_definitions.c
> +  strcpy(res_msg, buf);
```suggestion
  strcpy(res_msg, buf);

```

2021-04-14 20:16 UTC, devnoname120 commented on src/cmd_definitions.c
> +  {
```suggestion
  for (int i = 0; i < COUNT_OF(cmd_definitions); ++i) {
```

2021-04-14 20:16 UTC, devnoname120 commented on src/cmd_definitions.c
> +
```suggestion
```

2021-04-14 20:44 UTC, merged

2021-04-14 20:44 UTC, devnoname120 commented
Thanks!

2021-04-14 20:48 UTC, Jan200101 commented
as it stands there is still a problem
https://github.com/devnoname120/vitacompanion/blob/2b161ba2036083b99c7d0caa720f67a69e56a038/src/cmd.c#L68
this is where the resulting message will be copied and we essentially overflow the stack

2021-04-14 20:58 UTC, devnoname120 commented
Ah indeed, feel free to increase the size of this buffer.

2021-04-14 21:04 UTC, Jan200101 commented
Is it really a good idea to just increase the buffer?
Someone will run into this again at some point and perhaps it is better to revamp the thing to work with pointers instead of a predefined char array
https://github.com/Jan200101/vitacompanion/commit/99fabc868537b985d5191085db8ea80ebbd4dda8

2021-04-14 21:16 UTC, devnoname120 commented
I don't want to rely on the heap at all for this plugin.

2025-01-16 14:12 UTC, devnoname120 approved these changes