Kill application by title ID command
devnoname120/vitacompanion pull request #19
Opened 2023-12-16 22:49 UTC by buzzer-re

A simple but useful command, specially for development automation flows

2024-01-12 14:33 UTC, devnoname120 requested changes
Did you test your changes?

2024-01-12 14:33 UTC, devnoname120 commented on src/cmd_definitions.h
> +void cmd_launch(char **arg_list, size_t arg_count, char *res_msg);\
```suggestion
void cmd_launch(char **arg_list, size_t arg_count, char *res_msg);
```

2024-01-12 14:33 UTC, devnoname120 commented on src/cmd_definitions.c
> +    strcpy(res_msg, "Invalid argument number!");
```suggestion
```

The `arg_count` condition is useless as `cmd.c` already checks that.

2024-01-12 14:33 UTC, devnoname120 commented on src/cmd_definitions.c
> +  }
```suggestion
  if (sceAppMgrDestroyAppByName(arg_list[1]) < 0) {
    strcpy(res_msg, "Error: cannot kill the app. Is the TITLEID correct?\n");
  } else {
    strcpy(res_msg, "Killed.\n");
  }
```

- Sony's convention is `< 0` for errors. `> 0` are not considered errors.\
- You forgot the newline characters.

2024-01-25 14:09 UTC, buzzer-re commented
Yes

2024-01-25 19:02 UTC, devnoname120 approved these changes

2024-01-25 19:02 UTC, merged

2024-01-25 19:02 UTC, devnoname120 commented
Thanks